[package]
name = "wgpu-mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
kurbo = "0.11.0"
pollster = "0.3.0"
wgpu = { version = "22.0.0" }
winit = "0.30.4"
